### PR TITLE
fix: keep extension in migration name

### LINKED ISSUE #353: [v3 beta6] Migration names missing file extensions
Before the new globbing feature, Umzug stored the migration as the full filename (e.g. `123456-foo.js`) but with the new globbing feature it looks like it's storing the actual name of the migration without the file extension.

See line 371, which strips the file extension for the name
https://github.com/sequelize/umzug/blob/006036ae77ed6fbff9d06e89ad4690ff51a9c2a7/src/umzug.ts#L371-L376

And is then used as the migration name in the "name" column of the migration table
https://github.com/sequelize/umzug/blob/006036ae77ed6fbff9d06e89ad4690ff51a9c2a7/src/umzug.ts#L272

This introduces a major breaking change in existing Umzug installations as the name is different and thus tries to apply every migration again and ends up adding duplicate migrations to the migration table.

| name |
|------|
| 123456-foo |
| 123456-foo.js |

### PR DESCRIPTION
**Pull request by mmkal**
Fixes #353

### CODE REVIEW

File: src/umzug.ts [hunk 1]
```diff
@@ -368,7 +368,7 @@ export class Umzug<Ctx> extends EventEmitter {
 			const paths = await globAsync(globString, { ...globOptions, absolute: true });
 			return paths.map(unresolvedPath => {
 				const filepath = path.resolve(unresolvedPath);
-				const name = path.basename(filepath, path.extname(filepath));
+				const name = path.basename(filepath);
```
Comment (mmkal) [inline src/umzug.ts:371]: my only concern is that I have no idea why I did this is in the first place; it's more effort than doing nothing 🤷‍♂️

Comment (papb) [reply src/umzug.ts:371]: Also by the way I slightly prefer `path.parse(filepath).name` instead of `path.basename(filepath, path.extname(filepath))` (it's the same thing)

**Review by papb — APPROVED** [review]
